metadatautils Kodi 19 / Python 3 compatibility (#38)
* script.module.metadatautils 1.0.28

* more Python 3 fixes

* remove pycache

* fix missing semicolon, more imports, ...

* even more python 3 fixes

* Check for uniqueid and still more Python 3 fixes

* Add bs4 requirement to addon.xml

* Fix exception logging for Python 3

* v1.0.29 Remove python requirement for Kodi 18/19 compat

* utils.py: replace iconImage with setArt()

iconImage replaced by setArt() in Kodi 19

* tmdb.py: replace iconImage with setArt()

iconImage replaced by setArt() in Kodi 19

* pvrartwork.py: replace iconImage with setArt() and fix other runtime errors

Lines #393, #395 and #396 commented out to remove error:
    File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 393, in lookup_tvdb
    network = item["network"].lower().replace(" ", "")
    AttributeError: 'NoneType' object has no attribute 'lower'

Lines #408 and 409 commented out to remove error:
    File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 408, in lookup_tvdb
    if item["overview"]:
    KeyError: 'overview'

Line #422 changed to remove error and to replace iconImage with setArt():
File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 422, in lookup_tvdb
    listitem = xbmcgui.ListItem(label=item["seriesName"], label2=item["overview"])
    KeyError: 'overview'

* pvrartwork.py: workaround to get the "auto refresh" feature working

To get TMDB and TVDB auto lookup working needed to change setup of "selecttitle"
Additionally, for TVDB had to force "manual_select" to be set to true for the look up. No idea why.

* addon.xml: bump version number

* pvrartwork.py: fix for "Manual Configure Artwork" option

Removed "from utils import manual_set_artwork" and copied code from utils.py

* pvrartwork.py: tidy up fix for "Manual Configure Artwork" option

* addon.xml: bump version to 1.0.29.106

* pvrartwork.py: apply better fix for "Configure Manual Artwork"

1. revert previous "Configure Manual Artwork" changes
2. fix import statement in def manual_set_pvr_artwork (line #221)

* addon.xml: bump version number and update news

* addon.xml: cosmetic changes

* addon.xml: cosmetic changes

* pvrartwork.py: improve earlier fix

Reinstate code to improve score if channel name matches. Further investigation showed that error only occurs in certain conditions (e.g. when channel = "BBC News", with many aliases)

* pvrartwork.py: improve previous fixes to run time errors

* pvrartwork.py: fix display of artwork when performing a manual select in tvdb_lookup

* addon.xml: bump version

* Update addon.xml

* google.py: replace iconImage with setArt()

* animatedart.py: replace iconImage with setArt()

* animatedart.py: replace iconImage with setArt() (part 2)

* Update addon.xml

* pvrartwork.py: improve"scoring" in lookup_tvdb

ignore FHD, HD and SD in channel name in scoring algorithm

* pvrartwork.py: lookup_tvdb - tweak previous change to scoring

* pvrartwork.py: additional fixes

get_pvr_artwork:
- reinstate original creation of str searchtitle to replace/strip characters in title
- use searchtitle (with stripped/replaced characters) when performing initial search of cache)
- set cache expiration to 365 days for all lookups
get_searchtitle:
- comment out code to strip characters (seems to always return blanks - don't know why)
- update addon settings to replace ": " with " " to strip ":" from title (e.g. in Live: Test Cricket)

* Bump version to 1.0.31

* v1.0.32
- Remove python requirement for Kodi 18/19 compat
- Change imdb Top250 parsing from lxml to html.parser
- replace xbmc.translatePath with xmbcvfs.translatePath

* Replace ampersand

* v1.0.33 replace xbmc.LOGNOTICE with xbmc.LOGINFO as LOGNOTICE was removed

* v1.0.34 Set BeautifulSoup 3 dependency as optional to allow install on Matrix

* Set MusicBrainz dependency as optional

* v1.0.35: Remove BeautifulSoup3 dependency and use BeautifulSoup4 on Kodi 18 and 19 instead

Co-authored-by: berkhornet <67786207+berkhornet@users.noreply.github.com>