pvrartwork.py: replace iconImage with setArt() and fix other runtime errors
Lines #393, #395 and #396 commented out to remove error:
    File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 393, in lookup_tvdb
    network = item["network"].lower().replace(" ", "")
    AttributeError: 'NoneType' object has no attribute 'lower'

Lines #408 and 409 commented out to remove error:
    File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 408, in lookup_tvdb
    if item["overview"]:
    KeyError: 'overview'

Line #422 changed to remove error and to replace iconImage with setArt():
File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\helpers\pvrartwork.py", line 422, in lookup_tvdb
    listitem = xbmcgui.ListItem(label=item["seriesName"], label2=item["overview"])
    KeyError: 'overview'